- pyproject.toml
Remove "." from `[tool.ruff]` config for `src`.
Leaves only apis_ontology as directory when
considering first- vs. third-party imports.
> chore(deps): Ruff config: adapt src

- poetry.lock
- pyproject.toml
Reverts commits introduced in #37 (as per communication elsewhere, since the changes didn't solve the issue with connecting to the Postgres cluster).
> Revert back to psycopg

- apis_ontology/tables.py
Add base table for all entity classes, a custom column, table classes for all entity model classes.
> Add tables.py

- apis_ontology/settings.py
default settings currently uses CSP and XFrameOptionsMiddleware. To be able to set the headers in one middleware only this removes XFrameOptions until its fixed upstream.
> fix: overwrite `MIDDLEWARE` to fix settings for iframes

- apis_ontology/importers.py
Set `PersonImporter` to inherit from `BaseEntityImporter` instead of `GenericModelImporter`, like other existing importers/importer stubs.
Closes: #100
> fix(importers): inherit from BaseEntityImporter

- apis_ontology/settings.py
Keep `MIDDLEWARE` inherited from apis-acdhch-default-settings as is to be able to confirm effectiveness of updated CSP settings.
Fixes: #107
> fix(settings): do not remove clickjacking MIDDLEWARE

- apis_ontology/settings.py
Save `apis_core` dependencies needed in `INSTALLED_APPS` to two separate lists for inclusion (before/after other dependencies). Check for their presence before adding them to the (inherited) installed apps to prevent the Django app from failing to run (due to dependency duplication).
> fix(settings): check for APIS apps in INSTALLED_APPS

- apis_ontology/settings.py
Add `DJANGO_TABLES2_TABLE_ATTRS` config for
striped and hoverable table rows for better
usability.
Resolves: #130
> feat(settings): add django-tables2 settings

- apis_ontology/tables.py
For custom column `SortableLinkifyColumn`, which
provides linkification of individual objects,
update the reference to the accessor's `content_type` prior to upgrading `apis-core-rdf` to `v0.39.0`,
which removes `self_contenttype` from `RootObject`.
> refactor(tables): update column accessor args

- apis_ontology/management/commands/import_poster_data.py
Also set `title` variable empty by default to avoid errors based on possible `null` values in raw data.
> fix(posters_import): set leftover variable empty as fallback

- apis_ontology/rdfimport/WorkFromDNB.toml
When querying GND for `Work` data, use `DISTINCT` for data returned for `firstAuthor` to avoid duplication of `Uris` for same author.
> fix(rdfimport): SELECT DISTINCT authors for Works

- apis_ontology/models.py
Add `full_name` method to `Person` entity class to combine a person's `forename` and `surname` into a single string of the format "Forename Surname".
Return this method when the model's `__str__` method is called.
Closes: #60
> feat(models): add Person full_name method

- apis_ontology/tables.py
Add (sortable, linkified) custom `full_name` column as default column to `Person` table, replacing
custom `surname` column.
Since `surname` remains included in table Meta variable `fields`, the corresponding column is merely "downgraded" to a regular non-linkified column.
Builds on `full_name` method in `Person` model class, i.e. follows #125.
> feat(tables): add Person full_name column

- apis_ontology/settings.py
Remove `CSP_FRAME_ANCESTORS` variable, which is already being set in apis-acdhch-default-settings dependency.
> feat(settings): remove redundant CSP config

- apis_ontology/management/commands/import_poster_data.py
Save `quantity` data to `Poster` field of the same name. In theory, our preliminary records of posters should never not include an actual number of physical items in the archive, but the raw data does contain `null` values, in which case the fallback is `0`.
Non-integer values are converted to integers where possible, or otherwise appended to `notes`.
Resolves: #165
> feat(posters_import): save Poster quantity

- apis_ontology/management/commands/import_poster_data.py
For `Posters` without `event_type`, record all data which would normally be linked to a related `Event`/`Performance` in the `Poster` object's `notes` field to prevent data loss.
> feat(posters_import): save all data for event-less Posters

- apis_ontology/management/commands/import_poster_data.py
Save `signature` to dedicated field rather than
appending it to `notes` field.
> feat(posters_import): save signature to Poster field

- apis_ontology/management/commands/import_poster_data.py
Record unknown `event_type` in `Poster` `notes` field at the same time as other missing or unexpected data rather than leaving it until the end.
> refactor(posters_import): record unknown event_type early

- apis_ontology/management/commands/import_poster_data.py
Look up the `Event` object a `Poster` object
is related to via `PosterPromotedEvent` rather
than saving only its ID.
> feat(posters_import): look up related event

- apis_ontology/management/commands/import_poster_data.py
Retrieve the actual `Performance` object when an existing `PosterPromotedPerformance` relation is found and rename the variable used for querying the relation so as not to confuse the two (which is currently the case in a later log message, which references the relation object rather than the intended entity object).
> fix(posters_import): add missing query/fix object reference

- apis_ontology/management/commands/import_poster_data.py
Create first `Person` object for Thomas Bernhard only once import of OpenRefine `Poster` data has actually started, i.e. when the file is read, rather than doing so separately.
> refactor(posters_import): move initial Person object creation

- apis_ontology/management/commands/import_poster_data.py
Log missing `Poster` `label` (due to empty `title`) only after object creation, and only if object was actually created, not if it was just retrieved.
Also drop logging of additional information on missing `title` since we now save all of that to `notes`
anyway.
> feat(posters_import): log missing data after object creation

- apis_ontology/management/commands/import_poster_data.py
Log instances of `Poster` `quantity` being set to
zero on initial object creation.
> feat(posters_import): log Poster quantity of zero

- apis_ontology/management/commands/import_poster_data.py
Rename variable which is used to reference if a `Poster` was created or not for later reuse (since we currently indiscriminately use "created" for all of those).
> refactor(posters_import): rename variable for object creation

- apis_ontology/management/commands/import_poster_data.py
Log missing or unknown `Poster` `event_type` – which has missing `Event`/`Performance` relation as consequence – only after inital `Poster` creation.
> feat(posters_import): log event_type problems after object creation

- apis_ontology/management/commands/import_poster_data.py
Log information about `Performance` object affected by missing relation `PerformanceHadDirectorGroup` so the log message is more useful.
> feat(posters_import): log Performance on missing relation

- apis_ontology/management/commands/import_poster_data.py
Warn when `Performance` has no director, including when OpenRefine data contains GND references (since it's possible that no entities can be created due
to unexpected object types).
> fix(poster_import): always log missing directors

- apis_ontology/management/commands/import_poster_data.py
When debug logging the `title` of the `Poster` to
import, also always log the current row of the
OpenRefine raw data which is being imported.
> feat(posters_import): log data row alongside title

- apis_ontology/management/commands/import_poster_data.py
For `Posters` without a (valid) `event_type`, only record non-empty start and/or end dates
> fix(posters_import): record only valid dates in notes

- apis_ontology/management/commands/import_poster_data.py
If `Poster` `year` value is not reflected in the dates used for `date_range`, record the affected date(s) in `Poster` `notes` as this might be a hint that data was input incorrectly when it was collected manually.
> feat(posters_import): record inconsistent dates

- apis_ontology/management/commands/import_poster_data.py
When there is ambiguity between `year` and `end_date`, the latter is currently labelled incorrectly when
saved in `notes`. This updatese "Start" to "Ende".
> fix(posters_import): date label in notes

- apis_ontology/management/commands/import_poster_data.py
Add function to extract data from OpenRefine dictionaries to include in `Poster` `notes` when it cannot be included in objects directly.
> feat(posters_import): add function to extract OpenRefine data

- apis_ontology/management/commands/import_poster_data.py
- apis_ontology/utils.py
Move a number of helper/utility functions used in
management command for importing posters to new
`utils.py` file.
> refactor(posters_import,utils): move helper functions to utils.py

- apis_ontology/importers.py
When `date_of_birth` and `date_of_death` are returned for a `Person` from an external resource, they are assumed to have a length when actually, the keys may be present in the dataset but contain no values (i.e. be empty lists).
This commit fixes this by checking for truthiness of the values for DOB and DOD.
Resolves: #224
> fix(importers): fix date data mangling for PersonImporter

- apis_ontology/settings.py
Move `apis_history` before apps in `apis-acdhch-default-settings` following a recent change to history templates in Core, which requires history to be further up the chain of apps.
> feat(settings): update order of INSTALLED_APPS

- .gitignore
Exclude `locale` directories from earlier ignore
rule for files containing the word "local" (for
e.g. local settings) since this is the default
name given to directories for translation files
by Django.
> chore(gitignore): do not ignore locale directories

- apis_ontology/settings.py
Remove `history` dependency in anticipation of it
getting included in `apis-acdhch-default-settings` v2.6.0.
> feat(settings): remove history

- .gitignore
Ignore `apis_acdhch_default_settings` directory
so the `apis-acdhch-default-settings` dependency
can be symlinked during local development.
> chore(gitignore): ignore apis_acdhch_default_settings

- apis_ontology/models.py
Rename `TextChoices` constant used in `Event`
model class inner class `EventTypes` to match
the value it represents.
The current (nonsensical) variable name is
probably an accidental carryover from a
previous project.
> refactor(models): update TextChoices constant

- apis_ontology/settings.py
Remove `apis_core.relations` from `INSTALLED_APPS` setting in project since it's already being added
by `apis_acdhch_default_settings`, whose settings we are (re)using.
> feat(settings): remove relations from INSTALLED_APPS

- apis_ontology/settings.py
Add `LANGUAGES` to settings and set it to `de` for German to restrict the available app languages to
just German rather than having Django serve either English or German based on a user's browser settings (which `django.middleware.locale.LocaleMiddleware` does, which was recently added to the `MIDDLEWARE` setting in `apis-acdhcd-default-settings`).
> feat(settings): add LANGUAGES variable

- .gitignore
Ignore compiled versions of message files for
gettext (binary files compiled from .po files).
> chore(gitignore): ignore .mo files

- apis_ontology/models.py
Remove `__str__` methods from `Group` and `Place`
model classes since these already exist in the
Core classes that we are inheriting from.
> feat(models): remove redundant __str__ methods

- apis_ontology/models.py
- apis_ontology/settings.py
Update `Event` and `Work` model class methods
`rdf_configs` to use new RegEx format for RDF
imports following Core update (`v0.48.0`).
Also remove custom settings variable for location
of RDF configs (directory containing `.toml` files) since Core expects them in an app directory named
`triple_configs` by default anyway.
> feat(models): update rdf_configs

- apis_ontology/tables.py
Update `TitleFieldsMixin` `fields` value to include `other_title_information` as new default field/column in all tables which inherit from it.
> feat(tables): add new default field/column

- apis_ontology/filtersets.py
- apis_ontology/forms.py
Add `forms.py` and `filtersets.py` files and create form and filter exclusions for `Work` `tbit_category` field, since the field is not meant to be shown to users (used for work types/genres defined by TB in translation), but should have model validation applied to it, hence not setting it to `editable=False` in models.
Resolves: #302
> feat(forms,filters): exclude Work tbit_category field

- apis_ontology/tables.py
Drop `Person` table fields `forename` and `surname` as they already exist in the model class (in the same form). It's possible they were originally added
while experimenting with translation strings.
> feat(tables): remove superfluous fields

- apis_ontology/filtersets.py
- apis_ontology/locale/de/LC_MESSAGES/django.po
Update `BaseEntityFilterSet` class to modify the default combined search field included in `AbstractEntityFilterSet` so the form field's `label` and `help_text` are also translatable/translated (in addition to its `verbose_name`).
> feat(filters): expand parent filterset class for i18n

- .gitignore
Do not include `gettext` template files, which
may be present when `django-admin makemessages`
is run locally with `--keep-pot`.
> chore(gitignore): ignore .pot files

- .gitignore
Adapt exception from ignore rules for `locale` folder(s) so it only applies to subdirectories of `apis_ontology`, and update the preceding comment so it acts as section heading for excludes (similar to earlier comments which precede groups of ignore rules).
A less restrictive exception from the previously defined ignore rule for "local" files (meant to prevent inclusion of local settings, variables, versions of files) may cause build tools to include files belonging to other packages/ dependencies present during local development.
> chore(gitignore): narrow exception for locale folders

- pyproject.toml
- uv.lock
Split `dev` dependency group into sub groups to
separate linters/formatters from other dev tools.
> build: adapt uv dependency groups

- data/posters/FTB_posters_initial_catalogue_refined.json
Fix formatting of `Person` values in `Posters` raw data which leads to unintended duplication of data, which creates complications when trying to reimport data. The original value is missing a comma to separate
the `surname` and `forename` of a `Person` who appears in the dataset more than one.
> fix(data/posters): fix missing formatting for Person data

- data/posters/FTB_posters_initial_catalogue_refined.json
Update raw `Posters` data for a `Group` which appears in the dataset twice, but which is first imported
manually and only later (again) separately from GND, whose resulting two instances cannot be merged into one for some reason (trying to merge them results in a `content_type` mismatch  error).
This change adds the GND data from the one instance in the dataset as `match` value to the one without, which allows the two `Group` items to be recognised as being identical.
> feat(data/posters): add GND info to Group

- data/translations/translators.json
Update duplicate GND ID in translations raw data
to GND ID which matches other available data for
the object (`Person` `name` value).
> fix(data/translations): correct duplicate GND ID
